# Probabilidad y variables aleatorias

## Elementos de probabilidad

### Experimento y Espacio muestral 

En el contexto de la probabilidad, un **experimento** es definido como un proceso que genera resultados definidos. Y en cada una de las repeticiones del experimento, habrá uno y solo uno de los posibles resultados experimentales [@anderson, página 143]. 

**Ejemplo:**

```{r experimentos, echo=FALSE}
tabla = matrix(c("Lanzar una moneda",
                 "Tomar una pieza para inspeccionarla",
                 "Realizar una llamada de ventas",
                 "Lanzar un dado",
                 "Jugar un partido de fútbol",
                 "Cara, cruz",
                 "Con defecto, sin defecto",
                 "Hay compra, no hay compra",
                 "1, 2, 3, 4, 5, 6",
                 "Ganar, perder, empatar"),
               byrow = F, ncol = 2)
kable(tabla, align = 'l', booktabs = TRUE,
      caption = "Experimentos y resultados",
      col.names = c("Experimento", "Resultado experimental"), escape = FALSE) |>
  kable_styling(full_width = FALSE, bootstrap_options = c("condensed", "striped"), latex_options = c("HOLD_position"))

```

Al especificar todos los resultados experimentales posibles, está definiendo el **espacio muestral** de un experimento. En otras palabras, el espacio muestral de un experimentos es el conjunto de todos los resultados experimentales. Se usa la letra omega mayúscula ($\Omega$) para referirnos a este conjunto. Un elemento genérico de $\Omega$ se denota como $\omega$.

**Ejemplo:**

1. Conduciendo hacia su trabajo, una persona debe pasar por tres semáforos. En cada cruce la persona puede detenerse (D) o continuar (C), de acuerdo con el color de la luz. ¿Cuál es el espacio muestral del experimento?

$$\Omega = \lbrace CCC, DDD, CCD, CDD, CDC, DCD, DDC, DDD \rbrace$$
**Ejercicio:**

Determinar el espacio muestral de los siguientes experimentos:

1. Elegir un estudiante que está dentro de tu sala de clases (en este momento).
2. Pedir una orden (plato de fondo más entrada) en un local de comida, en cuyo menú tienen dos opciones de platos de fondo y dos de entradas.
3. 
4. 

### Eventos aleatorios

En principio, un **evento aleatorio** (o simplemente evento) es algún subconjunto del espacio muestral $\Omega$. Los eventos se anotan con una letra mayúscula a elección [@anderson, página 153].

A modo de ejemplo, consideren el experimento de lanzar un dado de 6 caras. Luego, determine el espacio muestral, y defina al menos 3 eventos, escribiendo su correspondiente conjunto.

$\Omega = \lbrace 1,2,3,4,5,6 \rbrace$

1. A: obtener un número par $\rightarrow A = \lbrace 2,4,6 \rbrace$
2.
3.

### Probabilidad de un evento

El concepto de probabilidad está asociado a la ocurrencia de un evento Sin embargo, el número que determina que tan factible es que dicho evento ocurra puede ser difícil de calcular. En este aspecto, como introducción, se hará uso de la definición clásica de probabilidad:

*Probabilidad de que ocurra un evento* $= \displaystyle\frac{\text{Casos favorables}}{\text{Casos totales}}$

Por ejemplo, la probabilidad de obtener un número par al lanzar un dado una vez es:

A: obtener un número par.

$$P(A) = \frac{\text{Casos favorables}}{\text{Casos totales}} = \frac{\lbrace 2,4,6 \rbrace}{\lbrace 1,2,3,4,5,6 \rbrace} = \frac{3}{6}= \frac{1}{2}$$
**Nota:** La probabilidad de cualquier evento siempre estará entre 0 y 1. Los casos extremos suceden cuando los casos favorables son inexistentes o son la totalidad de casos posibles respectivamente.

**Ejercicio:**

Calcular las siguientes probabilidades:

1. Se lanza un dado de 6 caras una vez. 
2. Sacar un número impar.
3. Que salga un 2 o un 5.
4. Sacar un valor menor que 4.
5. Obtener un valor menor o igual que 4.
6. Sacar un valor diferente de 3
7. Sacar un número menor a cero.
8. Sacar un número menor a siete
9. En una caja hay una pelota azul, una verde, una roja, una amarilla y una negra. ¿Cuál es la probabilidad de que, al sacar con los ojos cerrados una pelota de la caja, esta sea amarilla?
10. En un salón de clases hay 4 niños y 7 niñas. Si la maestra escoge al azar un estudiante de su salón, ¿cuál es la probabilidad de que el estudiante escogido sea una niña?

## Variable aleatoria



### Tipos de variables aleatorias
Al igual que sucede con las variables estadísticas, las variables aleatorias pueden ser discretas o continuas.

La variable número que sale al lanzar un dado con seis caras es una variable aleatoria discreta (toma los valores del 1 al 6).
La variable número de autos que pasan por un cruce en un tiempo determinado, es del tipo ...
La variable estatura se mueve en un rango de valores determinado por el mínimo y el máximo de la población, es del tipo ...


## Variables aleatorias discretas (v.a.d)

### Función de masa de probabilidad
### Función de distribución acumulada

### Distribuciones
#### Uniforme {.unlisted .unnumbered} 
#### Bernoulli {.unlisted .unnumbered}
#### Binomial {.unlisted .unnumbered} 
#### Poisson {.unlisted .unnumbered} 

## Variables aleatorias continuas (v.a.c)

### Función de densidad de probabilidad
### Función de distribución acumulada

### Distribuciones
#### Uniforme {.unlisted .unnumbered}
#### Exponencial {.unlisted .unnumbered} 
#### Normal {.unlisted .unnumbered} 
#### T - Student {.unlisted .unnumbered} 
#### Ji - Cuadrado {.unlisted .unnumbered}


## Esperanza

### v.a.d
### v.a.c

## Varianza

### v.a.d
### v.a.c


